spring.application.name=hobby-matching

# =======================================================
# [1] \uD504\uB85C\uD30C\uC77C \uC124\uC815
# =======================================================
# application-secret.properties \uD30C\uC77C\uC744 \uD3EC\uD568\uC2DC\uD0B5\uB2C8\uB2E4.
spring.profiles.include=secret

# =======================================================
# [2] \uB370\uC774\uD130\uBCA0\uC774\uC2A4 \uACF5\uD1B5 \uC124\uC815
# =======================================================
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =======================================================
# [3] JPA (Java Persistence API) \uC124\uC815
# =======================================================
# [\uC8FC\uC758] \uC2E4\uC81C \uC6B4\uC601 \uC11C\uBC84\uC5D0\uC11C\uB294 \uB370\uC774\uD130 \uC190\uC2E4/\uBCC0\uACBD\uC744 \uB9C9\uAE30 \uC704\uD574 'update' \uB300\uC2E0,
# \uD14C\uC774\uBE14 \uC0DD\uC131 \uC5EC\uBD80\uB9CC \uD655\uC778\uD558\uB294 'validate'\uB098 'none'\uC73C\uB85C \uC124\uC815\uD558\uB294 \uAC83\uC774 \uC548\uC804\uD569\uB2C8\uB2E4!
spring.jpa.hibernate.ddl-auto=update

# JPA\uAC00 \uC2E4\uD589\uD558\uB294 SQL \uCFFC\uB9AC\uB97C \uCF58\uC194\uC5D0 \uCD9C\uB825\uD569\uB2C8\uB2E4.
spring.jpa.show-sql=true

# SQL \uCFFC\uB9AC\uB97C \uBCF4\uAE30 \uC88B\uAC8C \uC815\uB82C\uD574\uC11C \uCD9C\uB825\uD569\uB2C8\uB2E4.
spring.jpa.properties.hibernate.format_sql=true

# =======================================================
# [4] \uD30C\uC77C \uC5C5\uB85C\uB4DC \uC124\uC815
# =======================================================
# \uD30C\uC77C \uC5C5\uB85C\uB4DC \uC6A9\uB7C9\uC744 \uC81C\uD55C \uC124\uC815\uC785\uB2C8\uB2E4.
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# \uD30C\uC77C \uC778\uCF54\uB529\uC744 UTF-8\uB85C \uC124\uC815\uD558\uC5EC \uD55C\uAE00 \uAE68\uC9D0\uC744 \uBC29\uC9C0\uD569\uB2C8\uB2E4.
spring.mandatory-file-encoding=UTF-8

# =======================================================
# [5] JWT (JSON Web Token) \uC124\uC815
# =======================================================
# \uD1A0\uD070 \uB9CC\uB8CC \uC2DC\uAC04 (\uBC00\uB9AC\uCD08 \uB2E8\uC704) - \uC608: 86,400,000 = 24\uC2DC\uAC04 , 1,800,000\uBC00\uB9AC\uCD08 = 30\uBD84
jwt.expiration=3600000